services:
  server:
    image: node:24
    container_name: whatsapp-stats
    ports:
      - "6767:4545"
    entrypoint: /bin/sh -c "cd /app && npm install -g pnpm && pnpm i && pnpm dev"
    working_dir: /app
    volumes:
      - .:/app
    restart: always
